name: cropper
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - icu=64.2
  - jpeg=9c
  - libclang=9.0.1
  - libffi=3.2.1
  - libiconv=1.15
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.33
  - openssl=1.1.1e
  - pcre=8.44
  - pip=20.0.2
  - pthread-stubs=0.4
  - pyside2=5.13.2
  - python=3.7.7
  - python_abi=3.7
  - qt=5.12.5
  - setuptools=46.1.1
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - h5py==2.10.0
    - numpy==1.18.2
    - opencv-python==4.2.0.32
    - pandas==1.0.3
    - python-dateutil==2.8.1
    - pytz==2019.3
    - shiboken2==5.14.1
    - six==1.14.0
    - tqdm==4.43.0

